/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/@__root'
import { Route as PublicLayoutRouteImport } from './routes/@_public/@layout'
import { Route as PrivateLayoutRouteImport } from './routes/@_private/@layout'
import { Route as PageRouteImport } from './routes/@page'
import { Route as PublicAuthLayoutRouteImport } from './routes/@_public/@auth/@layout'
import { Route as PublicMenuPageRouteImport } from './routes/@_public/@menu/@page'
import { Route as PrivateHomePageRouteImport } from './routes/@_private/@home/@page'
import { Route as PublicAuthVerificationPageRouteImport } from './routes/@_public/@auth/@verification/@page'
import { Route as PublicAuthSignUpPageRouteImport } from './routes/@_public/@auth/@sign-up/@page'
import { Route as PublicAuthSignInPageRouteImport } from './routes/@_public/@auth/@sign-in/@page'
import { Route as PublicAuthForgotPasswordPageRouteImport } from './routes/@_public/@auth/@forgot-password/@page'

const PublicLayoutRoute = PublicLayoutRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateLayoutRoute = PrivateLayoutRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const PageRoute = PageRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicAuthLayoutRoute = PublicAuthLayoutRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicMenuPageRoute = PublicMenuPageRouteImport.update({
  id: '/menu/',
  path: '/menu/',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PrivateHomePageRoute = PrivateHomePageRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PublicAuthVerificationPageRoute =
  PublicAuthVerificationPageRouteImport.update({
    id: '/verification/',
    path: '/verification/',
    getParentRoute: () => PublicAuthLayoutRoute,
  } as any)
const PublicAuthSignUpPageRoute = PublicAuthSignUpPageRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => PublicAuthLayoutRoute,
} as any)
const PublicAuthSignInPageRoute = PublicAuthSignInPageRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => PublicAuthLayoutRoute,
} as any)
const PublicAuthForgotPasswordPageRoute =
  PublicAuthForgotPasswordPageRouteImport.update({
    id: '/forgot-password/',
    path: '/forgot-password/',
    getParentRoute: () => PublicAuthLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PageRoute
  '/auth': typeof PublicAuthLayoutRouteWithChildren
  '/home/': typeof PrivateHomePageRoute
  '/menu/': typeof PublicMenuPageRoute
  '/auth/forgot-password/': typeof PublicAuthForgotPasswordPageRoute
  '/auth/sign-in/': typeof PublicAuthSignInPageRoute
  '/auth/sign-up/': typeof PublicAuthSignUpPageRoute
  '/auth/verification/': typeof PublicAuthVerificationPageRoute
}
export interface FileRoutesByTo {
  '/': typeof PageRoute
  '/auth': typeof PublicAuthLayoutRouteWithChildren
  '/home': typeof PrivateHomePageRoute
  '/menu': typeof PublicMenuPageRoute
  '/auth/forgot-password': typeof PublicAuthForgotPasswordPageRoute
  '/auth/sign-in': typeof PublicAuthSignInPageRoute
  '/auth/sign-up': typeof PublicAuthSignUpPageRoute
  '/auth/verification': typeof PublicAuthVerificationPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof PageRoute
  '/_private': typeof PrivateLayoutRouteWithChildren
  '/_public': typeof PublicLayoutRouteWithChildren
  '/_public/auth': typeof PublicAuthLayoutRouteWithChildren
  '/_private/home/': typeof PrivateHomePageRoute
  '/_public/menu/': typeof PublicMenuPageRoute
  '/_public/auth/forgot-password/': typeof PublicAuthForgotPasswordPageRoute
  '/_public/auth/sign-in/': typeof PublicAuthSignInPageRoute
  '/_public/auth/sign-up/': typeof PublicAuthSignUpPageRoute
  '/_public/auth/verification/': typeof PublicAuthVerificationPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/home/'
    | '/menu/'
    | '/auth/forgot-password/'
    | '/auth/sign-in/'
    | '/auth/sign-up/'
    | '/auth/verification/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/home'
    | '/menu'
    | '/auth/forgot-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verification'
  id:
    | '__root__'
    | '/'
    | '/_private'
    | '/_public'
    | '/_public/auth'
    | '/_private/home/'
    | '/_public/menu/'
    | '/_public/auth/forgot-password/'
    | '/_public/auth/sign-in/'
    | '/_public/auth/sign-up/'
    | '/_public/auth/verification/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PageRoute: typeof PageRoute
  PrivateLayoutRoute: typeof PrivateLayoutRouteWithChildren
  PublicLayoutRoute: typeof PublicLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/auth': {
      id: '/_public/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof PublicAuthLayoutRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/menu/': {
      id: '/_public/menu/'
      path: '/menu'
      fullPath: '/menu/'
      preLoaderRoute: typeof PublicMenuPageRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_private/home/': {
      id: '/_private/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof PrivateHomePageRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_public/auth/verification/': {
      id: '/_public/auth/verification/'
      path: '/verification'
      fullPath: '/auth/verification/'
      preLoaderRoute: typeof PublicAuthVerificationPageRouteImport
      parentRoute: typeof PublicAuthLayoutRoute
    }
    '/_public/auth/sign-up/': {
      id: '/_public/auth/sign-up/'
      path: '/sign-up'
      fullPath: '/auth/sign-up/'
      preLoaderRoute: typeof PublicAuthSignUpPageRouteImport
      parentRoute: typeof PublicAuthLayoutRoute
    }
    '/_public/auth/sign-in/': {
      id: '/_public/auth/sign-in/'
      path: '/sign-in'
      fullPath: '/auth/sign-in/'
      preLoaderRoute: typeof PublicAuthSignInPageRouteImport
      parentRoute: typeof PublicAuthLayoutRoute
    }
    '/_public/auth/forgot-password/': {
      id: '/_public/auth/forgot-password/'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password/'
      preLoaderRoute: typeof PublicAuthForgotPasswordPageRouteImport
      parentRoute: typeof PublicAuthLayoutRoute
    }
  }
}

interface PrivateLayoutRouteChildren {
  PrivateHomePageRoute: typeof PrivateHomePageRoute
}

const PrivateLayoutRouteChildren: PrivateLayoutRouteChildren = {
  PrivateHomePageRoute: PrivateHomePageRoute,
}

const PrivateLayoutRouteWithChildren = PrivateLayoutRoute._addFileChildren(
  PrivateLayoutRouteChildren,
)

interface PublicAuthLayoutRouteChildren {
  PublicAuthForgotPasswordPageRoute: typeof PublicAuthForgotPasswordPageRoute
  PublicAuthSignInPageRoute: typeof PublicAuthSignInPageRoute
  PublicAuthSignUpPageRoute: typeof PublicAuthSignUpPageRoute
  PublicAuthVerificationPageRoute: typeof PublicAuthVerificationPageRoute
}

const PublicAuthLayoutRouteChildren: PublicAuthLayoutRouteChildren = {
  PublicAuthForgotPasswordPageRoute: PublicAuthForgotPasswordPageRoute,
  PublicAuthSignInPageRoute: PublicAuthSignInPageRoute,
  PublicAuthSignUpPageRoute: PublicAuthSignUpPageRoute,
  PublicAuthVerificationPageRoute: PublicAuthVerificationPageRoute,
}

const PublicAuthLayoutRouteWithChildren =
  PublicAuthLayoutRoute._addFileChildren(PublicAuthLayoutRouteChildren)

interface PublicLayoutRouteChildren {
  PublicAuthLayoutRoute: typeof PublicAuthLayoutRouteWithChildren
  PublicMenuPageRoute: typeof PublicMenuPageRoute
}

const PublicLayoutRouteChildren: PublicLayoutRouteChildren = {
  PublicAuthLayoutRoute: PublicAuthLayoutRouteWithChildren,
  PublicMenuPageRoute: PublicMenuPageRoute,
}

const PublicLayoutRouteWithChildren = PublicLayoutRoute._addFileChildren(
  PublicLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PageRoute: PageRoute,
  PrivateLayoutRoute: PrivateLayoutRouteWithChildren,
  PublicLayoutRoute: PublicLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
